### ISSUE TITLE
Optimise (and FIX) the whole process

### ISSUE THREAD

**Issue by acs-ferreira** [Spudley/plg_user_notifyactivation#1]
Hi.

My Joomla activation process is the following:

1. User registers, e-mail is sent to the user
2. He receives an e-mail with a link to validate his e-mail
3. Once user has validated his e-mail, all Admins receives an email to activate account
4. If the account is activated by an admin trough the link on that e-mail requesting user account activation, notes are added by the plugin

It would be helpful if a note is added on **step 2**, since we never know if the user has validated his email on the admin panel.

So the note `User activated their own account via the link in the activation email` should be added on step 2, actually, it fires only **AFTER** step 3 _(once the whole account has been activated)_.

But, that note is **not correct**, as the user has been activated **by an Admin** after he (admin) have received an email like:

> Hello administrator,
> 
> A new user has registered at SITE.
> The user has verified their email address and requests that you approve their account.
> This email contains their details:
> 
> Name :  TEST
> Username:  test@gmail.com 
> 
> You can activate the user by selecting on the link below:
> https://www.example.com/register?task=registration.activate&token=c2d444e2a036ff947f62a701cced06bc

So the note, in this state, should be:

`User has been activated by an administrator via the link in the activation email`

### STEP 1
User registers, e-mail is sent (by Joomla) to the user

### STEP 2
He receives an e-mail with a link to validate his e-mail

> Hello TEST,
> 
> Thank you for registering at SITE. Your account is created and must be verified before you can use it.
> To verify the account select the following link or copy-paste it in your browser:
>  https://www.example.net/register?task=registration.activate&token=9181eaa63a05cc49e084b4f58087bcd6 
> 
> After verification an administrator will be notified to activate your account. You'll receive a confirmation when it's done.
> Once that account has been activated you may login to https://www.example.net/ using the following username and the password you entered during registration:
> 
> Username: myusername

### STEP 3
Once user has validated his e-mail, a note like `User activated their e-mail address via the link in the activation email`, then all Admins receives an email (sent by Joomla) to activate account like:

> Hello administrator,
> 
> A new user has registered at SITE.
> The user has verified their email address and requests that you approve their account.
> This email contains their details:
> 
> Name :  TEST
> Username:  test@gmail.com 
> 
> You can activate the user by selecting on the link below:
> https://www.example.com/register?task=registration.activate&token=c2d444e2a036ff947f62a701cced06bc

### STEP 4
If the account is activated by an admin trough the link on that e-mail requesting user account activation, a note like `User has been activated by an administrator via the link in the activation email` is added, OR

### STEP 5
If the account is activated by an admin trough the Joomla Admin Panel, a note like `User has been activated by %USERNAME% via the administration panel` is added

### STEP 6
User receives an e-mail (sent by Joomla) confirming that his account has been activated

> Hello USERNAME,
> 
> Your account has been activated by an administrator. You can now login at https://www.example.net/ using the username USERNAME and the password you chose while registering.

**Comment by Spudley** [comment]
Hi @acs-ferreira.

Thanks for raising the ticket and the awesome amount of detail you put into it. I really appreciate the time you put into writing it. I wish all tickets had this much detail.

I will review your suggestion today, and hopefully look to work on the code next week (time allowing).

**Comment by Spudley** [comment]
Hi @acs-ferreira.

I have now completed the changes to support the activation method you're using.

I had never used this activation method myself and I hadn't realised that it worked this way, with a verification email for the user and an activation email for the admins. Now that I've tried it and I understand what it does, I've been able to adjust the plugin to work with it.

I've tested the changes for a few examples, but I would really appreciate it if you could test it as well and confirm that it works for you before I close the ticket and make an official release.

One thing to note: When an admin user activates an account via email, it is impossible for the system to confirm which admin user it was who clicked on the link; they all get the same link, so the action is anonymous. I therefore can't put the admin user's name into the note in this case as I do for the other two activation/creation actions by admin users.

**Comment by acs-ferreira** [comment]
Hi.

The note on STEP 3 is stored, but not with the Subject.
See http://s11.postimg.org/70t7uutxf/screenshot_165.png

**Comment by Spudley** [comment]
@acs-ferreira: Re the missing messages in the screenshots. Go to the plugin config screen, and press "Save" to make sure the updated messages are stored properly when you've updated from the previous version. I had this issue during testing, and saving the config resolved it for me.

Please confirm if that helps. If not, I'll take another look in the code.

**Comment by acs-ferreira** [comment]
I confirm, it is OK 👍 
I think you can release it. :)

**Comment by Spudley** [comment]
Brilliant. Thank you for confirming.  :) I'll tag a release right after posting this.

Thanks again for raising the issue. I'm glad you find the plugin useful.

ps -- If you have a moment, please review the plugin on the JED.

**Comment by acs-ferreira** [comment]
You should add a link to the JED here: http://s18.postimg.org/540q7brbt/screenshot_168.png

**Comment by Spudley** [comment]
@acs-ferreira - I have added a link to the JED in the README.md file.
