### ISSUE TITLE
User doesn t get notified when i enable via the backend

### ISSUE THREAD

**Issue by nemanjaradevic** [Spudley/plg_user_notifyactivation#2]
Hello Friend 

If i paid you some money could you spare and spend some time into the issue to get it fixed?

I use rsforms pro to register users and i want a plugin to only be used to send emails to users when their account gets approved via the backend

**Comment by Spudley** [comment]
Hi.

The plugin isn't currently designed to send emails, but yes, I would be happy to make an addition to it to add this feature. If you are willing to pay for the work as you say then I will be able to get it done quickly. GitHub doesn't have private messaging so please contact me on twitter @Spudley99 and we can have a private conversation about this.

**Comment by Spudley** [comment]
Hi. Just to let you know that I have started work on this. Hoping to finish tomorrow, but if not then early next week.

**Comment by nemanjaradevic** [comment]
Cool thanks

**Comment by Spudley** [comment]
Hi. Sorry had no time on Friday, but have completed the work today. Please download the master version from the repository and confirm that it works for you as expected. When you have confirmed, I will close this ticket and formally mark it as a new release.

**Comment by nemanjaradevic** [comment]
you mean this one?

https://github.com/Spudley/plg_user_notifyactivation/releases

Spudley <https://github.com/Spudley> released this on 13 Dec 2016 · 2
commits
<https://github.com/Spudley/plg_user_notifyactivation/compare/2.0.0...master>
to master since this release

2.0.0


Regards

Nemanja Radevic
M:96388300
E:nemanja@radevic.com

**Comment by nemanjaradevic** [comment]
i downloaded but doesn t send a message once i enable users

maybe i download wrong stuff?

Regards

Nemanja Radevic
M:96388300
E:nemanja@radevic.com

**Comment by Spudley** [comment]
Hi.

No, not the 2.0 release; I didn't mark this update as a release yet.

Grab the master version from the repository -- https://github.com/Spudley/plg_user_notifyactivation/archive/master.zip

**Comment by nemanjaradevic** [comment]
click enabled and activate but no emails received



Regards

Nemanja Radevic
M:96388300
E:nemanja@radevic.com

**Comment by Spudley** [comment]
Hi. The emails need to be enabled in the plugin configuration; there is an "Email Sending" tab on the config page with options for three possible emails. The emails will only be sent if these options are switched on. Can you confirm whether you enabled them?

**Comment by nemanjaradevic** [comment]
my previous email i sent you screenshot attachments

where do these emails go?

to which email let s say there are more admins

isn t it better to put a box to which admin email the emails should go?

Regards

Nemanja Radevic
M:96388300
E:nemanja@radevic.com

**Comment by Spudley** [comment]
Hi.

Your email went to the Github issue not to me, and the attachment wasn't included so I haven't seen it. Sorry for the confusion. Post your replies via github and you'll be able to attach your screenshot.

**Comment by nemanjaradevic** [comment]
Why not just give me an email address

Anyways i will try to do this via github, if i manage

**Comment by nemanjaradevic** [comment]
ok sent in twitter

Regards

Nemanja Radevic
M:96388300
E:nemanja@radevic.com

**Comment by Spudley** [comment]
Hi. Thanks for the tweet. Now I can see your screenshots and see what you're saying, I think I see the problem here.

My understanding of your requirement was that the user should get the email; that is, the *user being activated*, so anna@ in your example screenshot.

Can I check now: are you saying you actually want it to go to the site admin? In that case, no it doesn't do that. I can change it to do so if that is your requirement

In your twitter message, you asked which admin the email should go to. Joomla typically sends admin-level emails to all users that have the "Receive system emails" option switched on. I'll use that for deciding who to send this email to.

**Comment by nemanjaradevic** [comment]
I think i wrote wrong...

Anna@ didn t get the email

They should both receive a notification when user is manually activated

I m so sorry you are right

In any wase nobody got notified

I will download the zip file from the master link you sent me and try again
and get back to you

**Comment by Spudley** [comment]
Hello.

Apologies for the delay: I was very busy last week.

I have now made a further set of modifications to the plugin, allowing it to be configured to send notification emails to the site admins as well as to the end user.

Please download the latest update from the master branch (https://github.com/Spudley/plg_user_notifyactivation/archive/master.zip) and try it out.

You will see that the fields in the 'Email Sending' config tab now have options as follows:

    [Do NOT send email] [Send email to user] [Send email to admins] [Send email to user and admins]

I also found and fixed a bug in the previous version that prevented the user email from being sent.

Please give this version a try and let me know how you get on.

Thank you.

**Comment by nemanjaradevic** [comment]
Looks quite right!

it works with RS forms and without it , i tested on joomla 3.6.5

i hope there will not be issues on newer versions

Nice man

Regards

Nemanja Radevic
M:96388300
E:nemanja@radevic.com

**Comment by Spudley** [comment]
Brilliant. Thank you for confirming that. I will now close this ticket and officially release the new version.

I'll also contact you separately via twitter later on.  :)

I don't believe there should be any issues with future Joomla versions. (it is impossible to be sure, of course though, as they don't exist yet!). However, Joomla 3.7.0 is currently available as a beta release, so you could test against that now if you wanted to. See https://twitter.com/joomla/status/827248930702446595 for more info. They're expecting to release 3.7 officially in another two months (I'm not sure of the exact planned release date; sorry).
